# Generated by Django 4.1.3 on 2023-02-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyurtmaapp', '0002_delete_tanlangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=10)),
            ],
        ),
    ]
