# Generated by Django 4.1.3 on 2023-02-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0006_delete_tanlangan'),
        ('buyurtmaapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abv',
            name='test',
        ),
        migrations.AddField(
            model_name='abv',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.mahsulot'),
        ),
    ]
