# Generated by Django 4.1.3 on 2023-02-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0006_delete_tanlangan'),
        ('userapp', '0003_remove_profil_davlat'),
        ('buyurtmaapp', '0004_remove_abv_test_abv_mahsulot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.mahsulot')),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
            ],
        ),
        migrations.DeleteModel(
            name='ABV',
        ),
    ]
