# Generated by Django 4.1.3 on 2023-02-20 09:27

import buyurtmaapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_profil_davlat'),
        ('asosiyapp', '0006_delete_tanlangan'),
        ('buyurtmaapp', '0005_tanlangan_delete_abv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField(default=1, validators=[buyurtmaapp.models.validate_miqdor])),
                ('umumiy', models.PositiveIntegerField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.mahsulot')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
            ],
        ),
    ]
