# Generated by Django 4.1.3 on 2023-02-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmaapp', '0007_buyurtma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='savat',
            field=models.ManyToManyField(related_name='savatlari', to='buyurtmaapp.savat'),
        ),
    ]
