# Generated by Django 4.1.3 on 2023-02-16 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0002_alter_ichki_bolim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('brend', models.CharField(max_length=70)),
                ('batafsil', models.CharField(max_length=700)),
                ('kafolat', models.CharField(max_length=70)),
                ('yetkazish', models.CharField(max_length=70)),
                ('narx', models.PositiveSmallIntegerField()),
                ('chegirma', models.PositiveSmallIntegerField(default=0)),
                ('mavjud', models.BooleanField(default=True)),
                ('min_order', models.CharField(default='1 dona', max_length=30)),
                ('ichki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.ichki')),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='mahsulotlar')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.mahsulot')),
            ],
        ),
    ]
