# Generated by Django 4.1.3 on 2023-02-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0005_tanlangan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tanlangan',
        ),
    ]
