# Generated by Django 4.1.3 on 2023-02-17 04:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='davlat',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
