# Generated by Django 4.1.3 on 2023-02-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profil_davlat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='davlat',
        ),
    ]
